name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'boards/**'
      - 'builder/**'
      - 'extend/**'
      - 'examples/**'
      - '**.json'
      - '**.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "counter"
          - "blink"
          - "leds"
        package: ["pio","qio"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install qio
        if: matrix.package == 'qio'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install file://.

      - name: Install pio
        if: matrix.package == 'pio'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

