name: CI

on:
  push:
    branches:
      - master
      - github_actions
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    if: github.repository == 'OS-Q/P01'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.7]
        tool:
          - "PIO"
          - "QIO"
        example:
          - "examples/counter"
          - "examples/leds"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success()
        run: |
          pio run -d ${{ matrix.examples }}
          echo "::set-output name=status::success"

    - name: Upload
      if: env.UPLOAD_BUILD == 'true' && steps.build.outputs.status == 'success' && !cancelled()
      uses: actions/upload-artifact@v2
      if: matrix.tool == 'QIO' && matrix.os == 'ubuntu-latest'
      with:
        name: P01
        path: ${{ matrix.examples }}/build
