name: PIO

on:
  push:
    branches:
      - pio
    paths:
      - 'boards/**'
      - 'builder/**'
      - 'examples/**'
      - 'platform.json'
      - 'platform.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "counter"
          - "leds"

        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

